### ISSUE TITLE
missing data sets

### ISSUE THREAD

**Issue by eotp** [jackdbd/geoviews-geopython-2018#1]
Dear Giacomo,

thanks for the very interesting talk at [Geopython 2018](http://2018.geopython.net/). I tried to reproduce the notebook, however I could not get the `basel_shapefiles`. Are you so kind and upload these shapefiles.

Thank you.

**Comment by jackdbd** [comment]
Hi @eotp  
thanks, I'm glad that you liked the talk.
I added the Basel shapefiles to the repository.
The netCDF is still not tracked under version control because it's a bit too big (26.5 MB). You can download it from the [NOAA website](https://www.esrl.noaa.gov/psd/repository/entry/show?entryid=synth%3Ae570c8f9-ec09-4e89-93b4-babd5651e7a9%3AL25jZXAucmVhbmFseXNpcy5kZXJpdmVkL3N1cmZhY2UvYWlyLm1vbi5tZWFuLm5j)
```
commit 7954f5c06f9aa6075ccca25158fca8b8e699561b
Author: jackdbd <jackdebidda@gmail.com>
Date:   Thu May 10 13:37:04 2018 +0200

    Add Basel shapefiles
```
